#!/bin/sh

#echo $alinearc | sed 's/ /\n/g'
#echo ${alinearc// /\n}
#sed 's/' '/\\n/' $alinearc

# make xfwm4 themes
dir=$PWD
cd $dir/alinea/xfwm4
./generator.py
cd $dir/alinea-blended/xfwm4
./generator.py
cd $dir/alinea-mini/xfwm4
./generator.py

replace() {
sed "s/#$1/$1/" themerc > /tmp/themerc.tmp && mv -f /tmp/themerc.tmp themerc
}

# build variants
source='alinea alinea-mini alinea-blended'

set $source
until [ $# == 0 ]
do
cd $dir
mkdir -p $1-dark-text/xfwm4
cd $dir/$1-dark-text/xfwm4
cp -r -u -v $dir/$1/xfwm4/* ./
replace 'active_text_color'
shift
done
