#!/bin/sh

#echo $alinearc | sed 's/ /\n/g'
#echo ${alinearc// /\n}
#sed 's/' '/\\n/' $alinearc

# make xfwm4 themes
cd alinea/xfwm4
./generator.py
cd ../../alinea-blended/xfwm4
./generator.py
cd ../../alinea-mini/xfwm4
./generator.py

replace() {
sed 's/#active_text_color/active_text_color/' $1/xfwm4/themerc > /tmp/themerc.tmp && mv -f /tmp/themerc.tmp $1/xfwm4/themerc
}

# make alinea-dark-text variant
mkdir alinea-dark-text
cp -r -u -v alinea/* alinea-dark-text
replace 'alinea-dark-text'

# make alinea-mini-dark-text variant
mkdir alinea-mini-dark-text
cp -r -u -v alinea-mini/* alinea-mini-dark-text
replace 'alinea-mini-dark-text'

# make alinea-blended-dark-text variant
mkdir alinea-blended-dark-text
cp -r -u -v alinea-blended/* alinea-blended-dark-text
replace 'alinea-blended-dark-text'

#file.tmp && mv -f file.tmp '$file'

# create links
#./link.sh
